print("Hello World!")
print("                /\       ")
print("               /  \      ")
print("              /    \     ")
print("             /      \    ")
print("             |   __  |   ")  
print("             |  |  | |   ")
print("             |  |  | |   ")
print("-----------------------------------------------------------")